config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :pages
  resources :workspaces

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  attribute :workspace
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :password, validations: true

  validates :email, presence: true, uniqueness: true

  normalizes :email, with: ->(email) { email.strip.downcase }
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate

    helper_method :current_user, :signed_in?
  end

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout
    Current.user = nil
    reset_session
  end

  def current_user
    Current.user ||= authenticate_from_session
  end

  def authenticate_from_session
    User.find_by(id: session[:user_id])
  end

  def authenticate
    redirect_to login_path unless signed_in?
  end

  def signed_in?
    current_user.present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:workspace_id, :user_id, :title, :frontpage, :ancestry)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate

  def new; end

  def create
    if (user = User.authenticate_by(email: params[:email], password: params[:password]))
      login(user)
      redirect_to root_path
    else
      flash.now[:error] = "Invalid email/password combination"
      render :new, status: :unauthorized
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate
  layout "sessions"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      flash.now[:error] = "Invalid email/password data"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspace, only: %i[ show edit update destroy ]

  # GET /workspaces or /workspaces.json
  def index
    @workspaces = Workspace.all
  end

  # GET /workspaces/1 or /workspaces/1.json
  def show
  end

  # GET /workspaces/new
  def new
    @workspace = Workspace.new
  end

  # GET /workspaces/1/edit
  def edit
  end

  # POST /workspaces or /workspaces.json
  def create
    @workspace = Workspace.new(workspace_params)

    respond_to do |format|
      if @workspace.save
        format.html { redirect_to workspace_url(@workspace), notice: "Workspace was successfully created." }
        format.json { render :show, status: :created, location: @workspace }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workspaces/1 or /workspaces/1.json
  def update
    respond_to do |format|
      if @workspace.update(workspace_params)
        format.html { redirect_to workspace_url(@workspace), notice: "Workspace was successfully updated." }
        format.json { render :show, status: :ok, location: @workspace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workspaces/1 or /workspaces/1.json
  def destroy
    @workspace.destroy!

    respond_to do |format|
      format.html { redirect_to workspaces_url, notice: "Workspace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workspace
      @workspace = Workspace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workspace_params
      params.require(:workspace).permit(:user_id, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/home/index.html.slim
.mx-auto.py-20.flex.flex-col.space-y-10 class="w-[550px]"
  h1 Home#index
  p Find me in app/views/home/index.html.slim

  = button_to 'Logout', logout_path, method: :delete, class: 'clean link'

  .field_with_errors
    input type='text'
    input type='email'
    input type='password'

app/views/layouts/application.html.slim
doctype html
html.h-full
  head.h-full
    title = content_for(:title) || "Notion Clone"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel="manifest" href="/manifest.json"
    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body.h-full
    = yield(:main).presence || yield

app/views/layouts/pages.html.slim
= content_for :main do
  .flex.h-full
    .lefcol.bg-stone-100 class="w-[240px]"
      p Menu
    .flex-1
      = yield

= render template: 'layouts/application'

app/views/layouts/sessions.html.slim
= content_for :main do
  .mx-auto.py-20 class="w-[450px]"
    = yield

= render template: 'layouts/application'

app/views/pages/_form.html.slim
= form_with(model: page) do |form|
  - if page.errors.any?
    div style="color: red"
      h2 = "#{pluralize(page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - page.errors.each do |error|
          li = error.full_message

  div
    = form.label :workspace_id, style: "display: block"
    = form.text_field :workspace_id

  div
    = form.label :user_id, style: "display: block"
    = form.text_field :user_id

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :frontpage, style: "display: block"
    = form.check_box :frontpage

  div
    = form.label :ancestry, style: "display: block"
    = form.text_field :ancestry

  div
    = form.submit

app/views/pages/_page.html.slim
div id="#{dom_id page}"
  p
    strong Workspace:
    =< page.workspace_id
  p
    strong User:
    =< page.user_id
  p
    strong Title:
    =< page.title
  p
    strong Frontpage:
    =< page.frontpage
  p
    strong Ancestry:
    =< page.ancestry

app/views/pages/edit.html.slim
h1 Editing page

== render "form", page: @page

br

div
  => link_to "Show this page", @page
  '|
  =< link_to "Back to pages", pages_path

app/views/pages/index.html.slim
p style="color: green" = notice

h1 Pages

#pages
  - @pages.each do |page|
    == render page
    p
      = link_to "Show this page", page

= link_to "New page", new_page_path

app/views/pages/new.html.slim
h1 New page

== render "form", page: @page

br

div
  = link_to "Back to pages", pages_path

app/views/pages/show.html.slim
p style="color: green" = notice

== render @page

div
  => link_to "Edit this page", edit_page_path(@page)
  '|
  =< link_to "Back to pages", pages_path

  = button_to "Destroy this page", @page, method: :delete

app/views/users/new.html.slim
= form_with model: @user, url: sign_up_path, class: 'flex flex-col space-y-4 border rounded-lg px-10 py-8 bg-white' do |f|
  - if flash[:error].present?
    .p-4.border.border-red-700.rounded.bg-red-50.text-center
      .text-red-500 = flash[:error]

  = f.label :email
  = f.email_field :email, value: params.dig('user', 'email')

  = f.label :password
  = f.password_field :password, value: params.dig('user', 'password')

  = f.label :password_confirmation
  = f.password_field :password_confirmation, value: params.dig('user', 'password_confirmation')

  br
  br

  = f.submit 'Sign up'
  = link_to 'Login &rarr;'.html_safe, login_path, class: 'text-center'

app/views/workspaces/_form.html.slim
= form_with(model: workspace) do |form|
  - if workspace.errors.any?
    div style="color: red"
      h2 = "#{pluralize(workspace.errors.count, "error")} prohibited this workspace from being saved:"
      ul
        - workspace.errors.each do |error|
          li = error.full_message

  div
    = form.label :user_id, style: "display: block"
    = form.text_field :user_id

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.submit

app/views/workspaces/_workspace.html.slim
div id="#{dom_id workspace}"
  p
    strong User:
    =< workspace.user_id
  p
    strong Title:
    =< workspace.title

app/views/workspaces/edit.html.slim
h1 Editing workspace

== render "form", workspace: @workspace

br

div
  => link_to "Show this workspace", @workspace
  '|
  =< link_to "Back to workspaces", workspaces_path

app/views/workspaces/index.html.slim
p style="color: green" = notice

h1 Workspaces

#workspaces
  - @workspaces.each do |workspace|
    == render workspace
    p
      = link_to "Show this workspace", workspace

= link_to "New workspace", new_workspace_path

app/views/workspaces/new.html.slim
h1 New workspace

== render "form", workspace: @workspace

br

div
  = link_to "Back to workspaces", workspaces_path

app/views/workspaces/show.html.slim
p style="color: green" = notice

== render @workspace

div
  => link_to "Edit this workspace", edit_workspace_path(@workspace)
  '|
  =< link_to "Back to workspaces", workspaces_path

  = button_to "Destroy this workspace", @workspace, method: :delete